### ISSUE TITLE
Can't set emmet-expand-jsx-className?

### ISSUE THREAD

**Issue by nukeop** [smihica/emmet-mode#104]
The variable `emmet-expand-jsx-className?` shows up when using `C-h v`, but not when I try `M-x set-variable`. Trying to `(setq emmet-expand-jsx-className? t)` in my init file also results in an error.

**Comment by thornjad** [comment]
What is the error?

**Comment by nukeop** [comment]
Looks like it works in the newest version, I'll close this.
