### ISSUE TITLE
Wrap with abbreviation

### ISSUE THREAD

**Issue by rafiks** [smihica/emmet-mode#111]
https://docs.emmet.io/actions/wrap-with-abbreviation/
is this working in Emacs or is this something that is a work in progress?

**Comment by pobocks** [comment]
So, https://github.com/smihica/emmet-mode/blob/master/src/mode-def.el#L507 is an I think partial implementation of this?  I don't think it lets you control placement within abbrev.

**Comment by rafiks** [comment]
thanks!
