### ISSUE TITLE
Change deprecated `cl` package dependency

### ISSUE THREAD

**Issue by DivineDominion** [smihica/emmet-mode#125]
When you load `emmet-mode` from ELPA, you will get a warning

    Package cl is deprecated

AFAIK we're all supposed to change dependencies to use `'cl-lib` instead.

**Comment by srj-github** [comment]
Hi, I have changed 'cl' to 'cl-lib' in both emmet.mode.el and emmet-mode.elc but now emmet is not working anymore. Everytime I press C-j it says `Symbol's function definition is void: every`.

Have you managed to get it working without that warning?

**Comment by DivineDominion** [comment]
I haven't tried to modify the code on my machine, yet. Maybe the `every` function is not part of `cl-lib` and we have to use `cl-loop` instead: https://www.gnu.org/software/emacs/manual/html_node/cl/Loop-Examples.html

Depends on the code where the error occurs!

**Comment by DivineDominion** [comment]
Actually, `cl-every` should do, see the changes to `deft` here: https://github.com/jrblevin/deft/pull/86/files
