### ISSUE TITLE
How to insert list with multiple items with a tags?

### ISSUE THREAD

**Issue by jcubic** [smihica/emmet-mode#132]
I want to create this list:

```html
<ul>
  <li class="item">
    <a href=""></a>
  </li>
  <li class="item">
    <a href=""></a>
  </li>
  <li class="item">
    <a href=""></a>
  </li>
</ul>
```

I've tried:

* `ul>(li.item_$*3)>a[href]` no a tag
* `ul>(li.item_$*3)>(a[href])` no a tag
* `ul>((li.item_$*3)>(a[href]))` empty ul
* `ul>li.item_$*3>a[href]` empty ul but with 3 empty lines
* `ul>(li.item_$*3>a[href])` same as above

Is there any way to create this HTML, or it's just a bug in Emmet?

**Comment by Timmymayes** [comment]
Should be: 	
`ul>(li.item>a)*3`

which outputs
`	<ul>
	    <li class="item"><a href=""></a></li>
	    <li class="item"><a href=""></a></li>
	    <li class="item"><a href=""></a></li>
	</ul>`

**Comment by jcubic** [comment]
Thanks, it's been a while since I've asked this question. I didn't use emmet that much, I need to give it a try again.

**Comment by Timmymayes** [comment]
I find it quite useful! I plan to commit some fixes and updates here when I get a chance. Figured a good start was answering some questions.

**Comment by jcubic** [comment]
@Timmymayes good way to start. But I'm not sure if this project is maintained and if you create a fix it will be merged. I've asked this question a year ago. It was so long ago that I've forgotten that ever used emmit, even that I have it installed.

**Comment by Timmymayes** [comment]
I'm in talks with the owner to maybe take it over one day. I'm new to web-dev myself and still learning full stack atm and try to utilize emmet in my works. I want to be a little more comfortable with elisp and emacs before taking over a package however.
