### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by snowleung** [smihica/emmet-mode#56]
I use ```emacs -nw``` start my emacs, and i get this:
error: Invalid modifier in string

and  ```emacs --debug-init``` log:
 1Debugger entered--Lisp error: (error "Invalid modifier in string")
 2  eval-buffer(#<buffer  *load*<2>> nil "/Users/samleung/.emacs.d/plugins/emmet-mode/emmet-mode.el" nil t)  ; Reading at buffer position 15964
 3  load-with-code-conversion("/Users/samleung/.emacs.d/plugins/emmet-mode/emmet-mode.el" "/Users/samleung/.emacs.d/plugins/emmet-mode/emmet-mode.el" nil t)
 4  require(emmet-mode)
 5  eval-buffer(#<buffer  *load*> nil "/Users/samleung/.emacs" nil t)  ; Reading at buffer position 326
 6  load-with-code-conversion("/Users/samleung/.emacs" "/Users/samleung/.emacs" t t)
 7  load("~/.emacs" t t)
 8  #[nil "^H\205\276^@   \306=\203^Q^@\307^H\310Q\202A^@ \311=\2033^@\312\307\313\314#\203#^@\315\202A^@\312\307\313\316#\203/^@\317\202A^@\315\202A^@   \32$
 9  command-line()
10  normal-top-level()

by the way, i start my emacs with window, it work well. why?

**Comment by pobocks** [comment]
@snowleung, have you had a chance to test if this is working for you now?

**Comment by snowleung** [comment]
@pobocks , I try, but fail, i use web mode instead of it.

**Comment by pobocks** [comment]
Have you updated to the latest version? It might not be working, but it
should at least be throwing a different error if it's not working.

**Comment by snowleung** [comment]
@pobocks yes, you are right, after i update emacs22 to emacs24, it work well.

**Comment by pobocks** [comment]
I'd actually meant the latest version of emmet-mode, but I'm glad that
fixed the problem!

**Comment by pobocks** [comment]
@smihica Do we have an "official" target for "oldest Emacs supported?"  If not, or if our oldest target is 23, I think we can close this.

**Comment by smihica** [comment]
@pobocks Thank you for your support.
I don't think we have had an "official" target for "oldest Emacs supported".
So Let's make it be 23. 22 is a little too old.
I think we can close this too.

**Comment by pobocks** [comment]
Ok.  I'll close this, and also add a note to the README to the effect of "supported from Emacs 23 forward".

**Comment by smihica** [comment]
:+1:
