### ISSUE TITLE
Does emment-mode support css colorization?

### ISSUE THREAD

**Issue by c02y** [smihica/emmet-mode#58]
[rainbow-mode](https://julien.danjou.info/projects/emacs-packages#rainbow-mode) and [web-mode](https://github.com/fxbois/web-mode) support css colorization(displays strings representing colors with the color they represent as background.), check the image in those pages.

Does emment-mode support this feature? If yes, how to set in `init.el`? If no, is there any plan?

**Comment by smihica** [comment]
Oh, It's really useful.Thank you for teaching me ;)

But emmet-mode doesn't support such a feature now.
And I think the feature is a little mismatch with emmet-mode's purpose.
emmet-mode have been developed for abbreviation of web cording.
Doesn't it work with emmet-mode as a minor-mode on Emacs?
