### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by helloncanella** [smihica/emmet-mode#63]
Hi. I've installed emmet-mode using the package repository on my emmacs, but I cant't expand it.

I've typed C-j, but nothing happens.

Could you help me? Thanks

**Comment by pobocks** [comment]
I'd be glad to try and help - can you give me a little more information?  At a minimum:

* What's the result of `M-x emacs-version`
* What mode is the buffer in? What minor modes are active?  These should be listed on your mode-line - if not, you can get this information via:

    ```
    M-x eval-expression<RET>
    minor-mode-list
    ```

It would also be helpful if you posted any configuration you have in your .emacs file; what mode-hooks you're attaching emmet-mode to, for example.

**Comment by helloncanella** [comment]
I appreciate your attention.

As requested, the results:

1. `M-x emacs-version`:  GNU Emacs 24.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.10.7) of 2014-03-07 on lamiak, modified by Debian

2. `minor-mode-list`: (show-paren-mode cua-mode tooltip-mode mouse-wheel-mode tool-bar-mode paragraph-indent-minor-mode use-hard-newlines menu-bar-mode file-name-shadow-mode global-font-lock-mode font-lock-mode blink-cursor-mode ...)

3. **.emacs file**

```
(put 'downcase-region 'disabled nil)
;;; Emacs is not a package manager, and here we load its package manager!
(require 'package)
(dolist (source '(("marmalade" . "http://marmalade-repo.org/packages/")
                  ("elpa" . "http://tromey.com/elpa/")
                  ;; TODO: Maybe, use this after emacs24 is released
                  ;; (development versions of packages)
                  ("melpa" . "http://melpa.milkbox.net/packages/")
                  ))
  (add-to-list 'package-archives source t))
(package-initialize)

 ;;(set-frame-parameter (selected-frame) 'alpha '(<active> [<inactive>]))
 (set-frame-parameter (selected-frame) 'alpha '(90 50))
 (add-to-list 'default-frame-alist '(alpha 90 50))

(eval-when-compile (require 'cl))
 (defun toggle-transparency ()
   (interactive)
   (if (/=
        (cadr (frame-parameter nil 'alpha))
        100)
       (set-frame-parameter nil 'alpha '(100 100))
     (set-frame-parameter nil 'alpha '(90 50))))
 (global-set-key (kbd "C-c t") 'toggle-transparency)

(add-to-list 'custom-theme-load-path "~/.emacs.d/color-theme/")
(load-theme 'monokai t)

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(cua-mode t nil (cua-base))
 '(custom-enabled-themes (quote (monokai)))
 '(custom-safe-themes (quote ("0eebf69ceadbbcdd747713f2f3f839fe0d4a45bd0d4d9f46145e40878fc9b098" default)))
 '(ede-project-directories (quote ("/home/hellon")))
 '(show-paren-mode t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
```

Once more, I thank you.

**Comment by pobocks** [comment]
From what I can see, you're not actually loading or starting emmet-mode anywhere.  I'd take a look at [the README](https://github.com/smihica/emmet-mode#2-settings-to-use) starting with section 2, where it describes how to configure emmet-mode.

Then, you can either follow the directions in section 3, or manually start emmet mode while in a markup or CSS major mode by doing `M-x emmet-mode`.

Let me know if this solves your problem.

**Comment by pobocks** [comment]
@helloncanella  - Did this resolve your problem?

**Comment by pobocks** [comment]
I'm going to close this issue - please comment if you're still having trouble, and we'll reopen it.

**Comment by mkde1** [comment]
Hi, I'm using emacs on OpenBSD and I cannot use emmet-mode.

-I have created a directory called "emmet-mode" in ".emacs.d" directory
-downloaded and put "emmet-mode.el" file inside "emmet-mode" directory
-added required lines(
(add-to-list 'load-path "~/emacs.d/emmet-mode")
(require 'emmet-mode)
) to "init.el" file inside ".emacs.d" directory
-when I do M-x emmet-mode
it gives [No match] alert in the command line.
