### ISSUE TITLE
emmet-expand-yas cannot be undone with undo-tree

### ISSUE THREAD

**Issue by louy2** [smihica/emmet-mode#64]
Reproduce steps:
1. `web-mode`
2. Type `html:5`
3. Hit `TAB`, confirm the snippet is expanded
4. Hit `ESC` to return to normal state
5. Hit `u` (undo-tree-undo)

Expected:
Snippet is deleted.

Actual:
Snippet stays.

_Messages_:

```
[yas] Snippet 2 exited.
Undo branch point!
```

`undo-tree-visualize` shows that two branches seemingly identical are created right after the snippet is expanded.

This is a issue reposted from: 
https://github.com/syl20bnr/spacemacs/issues/2351

**Comment by pobocks** [comment]
Are you using evil-mode?  I'm wondering if there's an interaction there, if
so.

In my Emacs, I wasn't able to replicate this.  In web mode, I expanded
html:5 (once with preview, once without), then ran undo-tree-undo, and it
seemed to work fine.

**Comment by louy2** [comment]
Yes I am. It is replicated by another evil user as well. But it's hard for me to imagine possible points of interaction.

**Comment by louy2** [comment]
Actually the order matters. If `ESC` is before expansion, it works.

**Comment by louy2** [comment]
It might be more complicated... I suspect it's an interaction between yasnippet and evil. Each redo creates a branch that adds to *Messages* the shown lines. Maybe I should test on more snippets.

**Comment by louy2** [comment]
Javascript if snippet with `yas-expand` works just fine. `emmet-expand-line` works fine. Just `emmet-yas-expand`.

**Comment by Sleepful** [comment]
I have this same issue with `undo-fu`.
`div` `TAB` `esc` `u` doesn't undo. 
You have to `2u` execute 2 undoes at once.
What gives? Looks like it undoes to a point where it automatically re-dos something.

**Comment by Sleepful** [comment]
looks like yas-snippet does some indentation after you *exit* a snippet, and undo is probably falling somewhere around there. Yas snippet code is a bit large so annoying to figure out.

**Comment by Sleepful** [comment]
alright!!!!! got it!!!!
`(setq yas-snippet-revival nil)`
