### ISSUE TITLE
Numbering expressions are not evaluated inside attribute expressions.

### ISSUE THREAD

**Issue by pobocks** [smihica/emmet-mode#65]
This:
```css
ul>li[id="thing-$"]*3
```

Should evaluate to:
```html
<ul>
  <li id="thing-1"></li>
  <li id="thing-2"></li>
  <li id="thing-3"></li>
</ul>
```

But instead evaluates to:
```html
<ul>
  <li id="thing-$"></li>
  <li id="thing-$"></li>
  <li id="thing-$"></li>
</ul>
```

I've verified that emmet does handle this case, so emmet-mode should.

**Comment by smihica** [comment]
Thank you pobocks. I've fixed it.

**Comment by pobocks** [comment]
Oh, sweet! I was gonna take a stab this weekend, so that's one less thing
to do ;-)
