### ISSUE TITLE
Wrapping individual lines in HTML tags

### ISSUE THREAD

**Issue by bk-m** [smihica/emmet-mode#81]
Wrapping individual lines in HTML tags as described [here](http://docs.emmet.io/actions/wrap-with-abbreviation/) doesn't work in emmet-mode.

Selecting several lines of text, hitting `C-c w` -> `ul>li*` -> `RET` should create a `ul` with an `li` for each line highlighted, instead emmet-mode seems to just ignore the `*` operator if you use it without a number.

I've further described the issue [here](http://emacs.stackexchange.com/questions/26835/emmet-mode-wrapping-individual-lines-in-html-tags)

**Comment by pobocks** [comment]
So, if you'll look above, you'll see a PR aimed at addressing this.  It's not suitable for production work yet, bc it doesn't do some token-replacement stuff, but I don't think it's more than an hour or two away from actually being suitable to merge.  I'm likely to get to it this week, I think.

**Comment by pobocks** [comment]
I've updated the PR, it should now contain more or less a working version of this, with tests.

I'm going to wait till I can go over it in daylight to merge it.

**Comment by pobocks** [comment]
So, since it can only affect this function, which I originally wrote, and I can't see anything wrong with it, I'm going to merge the change now.  Let me know if this works for you, @bk-m!
