### ISSUE TITLE
on-the-fly preview

### ISSUE THREAD

**Issue by Fuco1** [smihica/emmet-mode#83]
Hi.  Nowadays it's all the rage to have on-the-fly completions, previews etc.  I missed this feature with emmet, it would help a lot with visualizing what is going on.

Luckily this project is well designed so I was able to acomplish it with just these couple lines (including some trivial checks to not expand every word into a preview).

Would you be interested in somehow polishing this? I can start a Pull Request if needed.

``` elisp
(defun my-emmet-online-preview ()
  (ignore-errors
    (-when-let ((text beg end) (emmet-expr-on-line))
      (let ((wap (word-at-point)))
        (when (and (not (equal wap text))
                   (emmet-transform text))
          (emmet-preview beg end))))))
```

Add to the `post-self-insert-hook` like so:

``` elisp
(add-hook 'post-self-insert-hook 'my-emmet-online-preview t t)
```

It then updates the preview as I type, awesome!

**Comment by pobocks** [comment]
Hi Matus!  

That's very clever! I personally wouldn't want it on by default, but I'd vote for inclusion so long as it's controlled by a customize var (something like emmet-online-preview or something?)

**Comment by Fuco1** [comment]
All right, I'll do a PR when I get home from work :)

**Comment by hiddenlotus** [comment]
@Fuco1 Please do a PR. Thanks.

**Comment by Fuco1** [comment]
Totally forgot about this!  I'll try to schedule it asap :)
